from tkinter import*

win = Tk()
win.geometry('300x200')
win.title('FORMULARIO')
eti = Label(win, text='BIENVENIDOS', fg='blue')
eti.grid(row=0, column=0)
eti.config(font=('Arial', 16))
name = Label(win, text='Ingrese su NOMBRE')
name.grid(row=1, column=0)
name.config(padx=10, pady=10)
cuadro_name = Entry(win)
cuadro_name.grid(row=1, column=1)
last_name = Label(win, text='Ingrese su APELLIDO')
last_name.grid(row=2, column=0)
last_name.config(padx=10, pady=10)
cuadro_last_name = Entry(win)
cuadro_last_name.grid(row=2, column=1)
edad = Label(win, text='Ingrese su EDAD')
edad.grid(row=3, column=1)
edad.config(padx=10, pady=10)
cuadro_edad = Entry(win)
cuadro_edad.grid(row=3, column=1)
direcc = Label(win, text='Ingrese su DIRECCION')
direcc.grid(row=4, column=0)
direcc.config(padx=10, pady=10)
cuadro_direcc = Entry(win)
cuadro_direcc.grid(row=4, column=1)


win.mainloop()
